language: python
python:
  - 3.6

services:
  - docker

sudo: required

install:
  - pip install -r requirements-doc.txt

script:
  - docker run python:2.7 pip install . && python -c "import openmensa"
  - docker run python:3.6 pip install . && python -c "import openmensa"
  - cd doc
  - pydocmd build
  - cd ..

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: doc/_build/site
 on:
   branch: master
